### ISSUE TITLE
Web UI for authorizing GFT addresses

### ISSUE THREAD

**Issue by gmachtel** [nbh-digital/goldchain#29]
Web UI, can only be operated by NBH employees through wallet addresses created by them. 
Multisign 1 on x (x being all NBH addresses).

**Comment by GlenDC** [comment]
Seems out of scope for this repo.

**Comment by robvanmieghem** [comment]
A place where this might be apporpriate is the light desktop wallet even though I think authorizing addresses is more complex, it should be initiated by a user's 3bot and the authorized addresses should dripple to the chain, if not, they are all linked together in the same transaction, couplingthem to the same wallet.

**Comment by robvanmieghem** [comment]
from a chain perspective, having this functionality available in jumpscaleX is sufficient, the rest is indeed for another repo.
