### ISSUE TITLE
Create client to call NBH APIs

### ISSUE THREAD

**Issue by gmachtel** [nbh-digital/goldchain#33]
APIs to be called as client for 3bot usage (through the Vertex gateway):

[NewPosition](https://hybrid-solutions.kayako.com//index.php?/Knowledgebase/Article/View/5475) (back-end API to be used for conversion GFT to physical gold on NBH gold account)
[GetAccounts](https://support.hybridsolutions.com//index.php?/Knowledgebase/Article/View/1934) (front-end API to give overview of accounts with NBH IVS)
[GetAccountSummary](https://support.hybridsolutions.com//index.php?/Knowledgebase/Article/View/1953) (front-end API to give content on a NBH IVS account)
[GetNewTick](http://www.hybrid-solutions.com/support/index.php?/Knowledgebase/Article/View/1939) (front-end API to get a price)
[ClosePosition](https://hybrid-solutions.kayako.com//index.php?/Knowledgebase/Article/View/5479) (back-end API to be used for conversion physical gold on NBH gold account to GFT)

Non-prio: 
[Front-end NewOrder](https://hybrid-solutions.kayako.com//index.php?/Knowledgebase/Article/View/1952) 
(to be used for conversion fiat <--> physical gold, to be used when offering the link to fiat also in 3bot app)
[Back-end MoneyTransactions](https://hybrid-solutions.kayako.com//index.php?/Knowledgebase/Article/View/5393) 
(make any money transaction (Deposit , Withdrawal , Adjustment, Credit in , Credit out ) at specific account - not to be used in first phase, it's a pure back-end adjustment API)
[DeliverSymbol](url) 
(front-end API to deliver physical gold in a branch - not offered in NBH-Digital in first phase)

**Comment by GlenDC** [comment]
Duplicate issue of #31.
