### ISSUE TITLE
Requesting coins through API doesn't always succeed with large amounts

### ISSUE THREAD

**Issue by DylanVerstraete** [nbh-digital/goldchain#42]

**Comment by robvanmieghem** [comment]
I saw that the faucet simply sends tokens and that there is a banker binary on the server. @LeeSmet , can you point me to the source code for that?

**Comment by LeeSmet** [comment]
Banker has nothing to do with faucet, it is a binary I used to stress test rpc (rework), tx throughput...

**Comment by robvanmieghem** [comment]
@DylanVerstraete how were you feeding your faucet with tokens and can you paste the exact error here?

**Comment by robvanmieghem** [comment]
closing this issue as the faucet is a daemon with just a lot of gft, assuming that Dylan is mining
