### ISSUE TITLE
https://explorer.testnet.nbh-digital.com is down

### ISSUE THREAD

**Issue by robvanmieghem** [nbh-digital/goldchain#49]

**Comment by LeeSmet** [comment]
It seems the node itself is unreachable right now

**Comment by LeeSmet** [comment]
Zerotier UI seems to confirm that the node is down, went down apparently 1D2H15M ago.

**Comment by LeeSmet** [comment]
Node has been rebooted, explorer container service has been restarted automatically. Explorer is available again on the given url, and catching up with the network

**Comment by robvanmieghem** [comment]
thanks
