### ISSUE TITLE
Support burn transaction in frontend

### ISSUE THREAD

**Issue by DylanVerstraete** [nbh-digital/goldchain#52]
Currently not all coin inputs are shown:

[https://explorer.testnet.tfb.threefold.tech/hash.html?hash=6c64646cbb3f9cef3b5eb894a01e7407a599a99f2cfede3fa2464f116f6d8541](https://explorer.testnet.tfb.threefold.tech/hash.html?hash=6c64646cbb3f9cef3b5eb894a01e7407a599a99f2cfede3fa2464f116f6d8541)

**Comment by GlenDC** [comment]
You link wrong transaction, this already works. The bug you linked is related to rivine-chain-templates and that has been fixed in the meanwhile.
