### ISSUE TITLE
Align with Jimber

### ISSUE THREAD

**Issue by robvanmieghem** [nbh-digital/goldchain#58]

**Comment by GlenDC** [comment]
More info?

**Comment by robvanmieghem** [comment]
Meeting with Jimber to align on the backend integration specs

**Comment by robvanmieghem** [comment]
Jonas is going to add his remarks

**Comment by robvanmieghem** [comment]
https://github.com/nbh-digital/goldchain/commit/afa909af491f896154a8c1b49d03a25984c4123d
